// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: docksphinx/v1/docksphinx.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocksphinxService_GetSnapshot_FullMethodName = "/docksphinx.v1.DocksphinxService/GetSnapshot"
	DocksphinxService_Stream_FullMethodName      = "/docksphinx.v1.DocksphinxService/Stream"
)

// DocksphinxServiceClient is the client API for DocksphinxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocksphinxServiceClient interface {
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamUpdate], error)
}

type docksphinxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocksphinxServiceClient(cc grpc.ClientConnInterface) DocksphinxServiceClient {
	return &docksphinxServiceClient{cc}
}

func (c *docksphinxServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, DocksphinxService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docksphinxServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocksphinxService_ServiceDesc.Streams[0], DocksphinxService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocksphinxService_StreamClient = grpc.ServerStreamingClient[StreamUpdate]

// DocksphinxServiceServer is the server API for DocksphinxService service.
// All implementations must embed UnimplementedDocksphinxServiceServer
// for forward compatibility.
type DocksphinxServiceServer interface {
	GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error)
	Stream(*StreamRequest, grpc.ServerStreamingServer[StreamUpdate]) error
	mustEmbedUnimplementedDocksphinxServiceServer()
}

// UnimplementedDocksphinxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocksphinxServiceServer struct{}

func (UnimplementedDocksphinxServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedDocksphinxServiceServer) Stream(*StreamRequest, grpc.ServerStreamingServer[StreamUpdate]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedDocksphinxServiceServer) mustEmbedUnimplementedDocksphinxServiceServer() {}
func (UnimplementedDocksphinxServiceServer) testEmbeddedByValue()                           {}

// UnsafeDocksphinxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocksphinxServiceServer will
// result in compilation errors.
type UnsafeDocksphinxServiceServer interface {
	mustEmbedUnimplementedDocksphinxServiceServer()
}

func RegisterDocksphinxServiceServer(s grpc.ServiceRegistrar, srv DocksphinxServiceServer) {
	// If the following call panics, it indicates UnimplementedDocksphinxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocksphinxService_ServiceDesc, srv)
}

func _DocksphinxService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocksphinxServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocksphinxService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocksphinxServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocksphinxService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocksphinxServiceServer).Stream(m, &grpc.GenericServerStream[StreamRequest, StreamUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocksphinxService_StreamServer = grpc.ServerStreamingServer[StreamUpdate]

// DocksphinxService_ServiceDesc is the grpc.ServiceDesc for DocksphinxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocksphinxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docksphinx.v1.DocksphinxService",
	HandlerType: (*DocksphinxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _DocksphinxService_GetSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _DocksphinxService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docksphinx/v1/docksphinx.proto",
}
