// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: docksphinx/v1/docksphinx.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerId      string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName    string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ImageName        string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	State            string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenUnix     int64                  `protobuf:"varint,6,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	StartedAtUnix    int64                  `protobuf:"varint,7,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ComposeProject   string                 `protobuf:"bytes,9,opt,name=compose_project,json=composeProject,proto3" json:"compose_project,omitempty"`
	ComposeService   string                 `protobuf:"bytes,10,opt,name=compose_service,json=composeService,proto3" json:"compose_service,omitempty"`
	RestartCount     int32                  `protobuf:"varint,11,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	VolumeMountCount int32                  `protobuf:"varint,12,opt,name=volume_mount_count,json=volumeMountCount,proto3" json:"volume_mount_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerInfo) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerInfo) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerInfo) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *ContainerInfo) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *ContainerInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ContainerInfo) GetComposeProject() string {
	if x != nil {
		return x.ComposeProject
	}
	return ""
}

func (x *ContainerInfo) GetComposeService() string {
	if x != nil {
		return x.ComposeService
	}
	return ""
}

func (x *ContainerInfo) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ContainerInfo) GetVolumeMountCount() int32 {
	if x != nil {
		return x.VolumeMountCount
	}
	return 0
}

type ContainerMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsage   int64                  `protobuf:"varint,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit   int64                  `protobuf:"varint,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,5,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	NetworkRx     int64                  `protobuf:"varint,6,opt,name=network_rx,json=networkRx,proto3" json:"network_rx,omitempty"`
	NetworkTx     int64                  `protobuf:"varint,7,opt,name=network_tx,json=networkTx,proto3" json:"network_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMetrics) Reset() {
	*x = ContainerMetrics{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetrics) ProtoMessage() {}

func (x *ContainerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetrics.ProtoReflect.Descriptor instead.
func (*ContainerMetrics) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerMetrics) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryUsage() int64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ContainerMetrics) GetNetworkRx() int64 {
	if x != nil {
		return x.NetworkRx
	}
	return 0
}

func (x *ContainerMetrics) GetNetworkTx() int64 {
	if x != nil {
		return x.NetworkTx
	}
	return 0
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	CreatedUnix   int64                  `protobuf:"varint,5,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{2}
}

func (x *ImageInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ImageInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ImageInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageInfo) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

type NetworkInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NetworkId      string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Driver         string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	Scope          string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Internal       bool                   `protobuf:"varint,5,opt,name=internal,proto3" json:"internal,omitempty"`
	ContainerCount int32                  `protobuf:"varint,6,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkInfo) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *NetworkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *NetworkInfo) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *NetworkInfo) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *NetworkInfo) GetContainerCount() int32 {
	if x != nil {
		return x.ContainerCount
	}
	return 0
}

type VolumeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Mountpoint    string                 `protobuf:"bytes,3,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	RefCount      int32                  `protobuf:"varint,4,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	UsageNote     string                 `protobuf:"bytes,5,opt,name=usage_note,json=usageNote,proto3" json:"usage_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeInfo) Reset() {
	*x = VolumeInfo{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeInfo) ProtoMessage() {}

func (x *VolumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeInfo.ProtoReflect.Descriptor instead.
func (*VolumeInfo) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *VolumeInfo) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *VolumeInfo) GetRefCount() int32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *VolumeInfo) GetUsageNote() string {
	if x != nil {
		return x.UsageNote
	}
	return ""
}

type ComposeGroup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Project        string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Service        string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	ContainerIds   []string               `protobuf:"bytes,3,rep,name=container_ids,json=containerIds,proto3" json:"container_ids,omitempty"`
	ContainerNames []string               `protobuf:"bytes,4,rep,name=container_names,json=containerNames,proto3" json:"container_names,omitempty"`
	NetworkNames   []string               `protobuf:"bytes,5,rep,name=network_names,json=networkNames,proto3" json:"network_names,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComposeGroup) Reset() {
	*x = ComposeGroup{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeGroup) ProtoMessage() {}

func (x *ComposeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeGroup.ProtoReflect.Descriptor instead.
func (*ComposeGroup) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{5}
}

func (x *ComposeGroup) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ComposeGroup) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ComposeGroup) GetContainerIds() []string {
	if x != nil {
		return x.ContainerIds
	}
	return nil
}

func (x *ComposeGroup) GetContainerNames() []string {
	if x != nil {
		return x.ContainerNames
	}
	return nil
}

func (x *ComposeGroup) GetNetworkNames() []string {
	if x != nil {
		return x.NetworkNames
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	ContainerId   string                 `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ImageName     string                 `protobuf:"bytes,6,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *Event) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Event) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Event) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Containers    []*ContainerInfo             `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	Metrics       map[string]*ContainerMetrics `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Images        []*ImageInfo                 `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Networks      []*NetworkInfo               `protobuf:"bytes,4,rep,name=networks,proto3" json:"networks,omitempty"`
	Volumes       []*VolumeInfo                `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Groups        []*ComposeGroup              `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	RecentEvents  []*Event                     `protobuf:"bytes,7,rep,name=recent_events,json=recentEvents,proto3" json:"recent_events,omitempty"`
	AtUnix        int64                        `protobuf:"varint,8,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{7}
}

func (x *Snapshot) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Snapshot) GetMetrics() map[string]*ContainerMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Snapshot) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Snapshot) GetNetworks() []*NetworkInfo {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *Snapshot) GetVolumes() []*VolumeInfo {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Snapshot) GetGroups() []*ComposeGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Snapshot) GetRecentEvents() []*Event {
	if x != nil {
		return x.RecentEvents
	}
	return nil
}

func (x *Snapshot) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

type StreamUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamUpdate_Snapshot
	//	*StreamUpdate_Event
	Payload       isStreamUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUpdate) Reset() {
	*x = StreamUpdate{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUpdate) ProtoMessage() {}

func (x *StreamUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUpdate.ProtoReflect.Descriptor instead.
func (*StreamUpdate) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{8}
}

func (x *StreamUpdate) GetPayload() isStreamUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamUpdate) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*StreamUpdate_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *StreamUpdate) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*StreamUpdate_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isStreamUpdate_Payload interface {
	isStreamUpdate_Payload()
}

type StreamUpdate_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type StreamUpdate_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*StreamUpdate_Snapshot) isStreamUpdate_Payload() {}

func (*StreamUpdate_Event) isStreamUpdate_Payload() {}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{9}
}

type StreamRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IncludeInitialSnapshot bool                   `protobuf:"varint,1,opt,name=include_initial_snapshot,json=includeInitialSnapshot,proto3" json:"include_initial_snapshot,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docksphinx_v1_docksphinx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_docksphinx_v1_docksphinx_proto_rawDescGZIP(), []int{10}
}

func (x *StreamRequest) GetIncludeInitialSnapshot() bool {
	if x != nil {
		return x.IncludeInitialSnapshot
	}
	return false
}

var File_docksphinx_v1_docksphinx_proto protoreflect.FileDescriptor

const file_docksphinx_v1_docksphinx_proto_rawDesc = "" +
	"\n" +
	"\x1edocksphinx/v1/docksphinx.proto\x12\rdocksphinx.v1\"\xc0\x03\n" +
	"\rContainerInfo\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12$\n" +
	"\x0elast_seen_unix\x18\x06 \x01(\x03R\flastSeenUnix\x12&\n" +
	"\x0fstarted_at_unix\x18\a \x01(\x03R\rstartedAtUnix\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0fcompose_project\x18\t \x01(\tR\x0ecomposeProject\x12'\n" +
	"\x0fcompose_service\x18\n" +
	" \x01(\tR\x0ecomposeService\x12#\n" +
	"\rrestart_count\x18\v \x01(\x05R\frestartCount\x12,\n" +
	"\x12volume_mount_count\x18\f \x01(\x05R\x10volumeMountCount\"\x81\x02\n" +
	"\x10ContainerMetrics\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x03R\vmemoryUsage\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\x03R\vmemoryLimit\x12%\n" +
	"\x0ememory_percent\x18\x05 \x01(\x01R\rmemoryPercent\x12\x1d\n" +
	"\n" +
	"network_rx\x18\x06 \x01(\x03R\tnetworkRx\x12\x1d\n" +
	"\n" +
	"network_tx\x18\a \x01(\x03R\tnetworkTx\"\x8f\x01\n" +
	"\tImageInfo\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\fcreated_unix\x18\x05 \x01(\x03R\vcreatedUnix\"\xb3\x01\n" +
	"\vNetworkInfo\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1a\n" +
	"\binternal\x18\x05 \x01(\bR\binternal\x12'\n" +
	"\x0fcontainer_count\x18\x06 \x01(\x05R\x0econtainerCount\"\x94\x01\n" +
	"\n" +
	"VolumeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x03 \x01(\tR\n" +
	"mountpoint\x12\x1b\n" +
	"\tref_count\x18\x04 \x01(\x05R\brefCount\x12\x1d\n" +
	"\n" +
	"usage_note\x18\x05 \x01(\tR\tusageNote\"\xb5\x01\n" +
	"\fComposeGroup\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12#\n" +
	"\rcontainer_ids\x18\x03 \x03(\tR\fcontainerIds\x12'\n" +
	"\x0fcontainer_names\x18\x04 \x03(\tR\x0econtainerNames\x12#\n" +
	"\rnetwork_names\x18\x05 \x03(\tR\fnetworkNames\"\xc2\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x1d\n" +
	"\n" +
	"image_name\x18\x06 \x01(\tR\timageName\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x122\n" +
	"\x04data\x18\b \x03(\v2\x1e.docksphinx.v1.Event.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x04\n" +
	"\bSnapshot\x12<\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1c.docksphinx.v1.ContainerInfoR\n" +
	"containers\x12>\n" +
	"\ametrics\x18\x02 \x03(\v2$.docksphinx.v1.Snapshot.MetricsEntryR\ametrics\x120\n" +
	"\x06images\x18\x03 \x03(\v2\x18.docksphinx.v1.ImageInfoR\x06images\x126\n" +
	"\bnetworks\x18\x04 \x03(\v2\x1a.docksphinx.v1.NetworkInfoR\bnetworks\x123\n" +
	"\avolumes\x18\x05 \x03(\v2\x19.docksphinx.v1.VolumeInfoR\avolumes\x123\n" +
	"\x06groups\x18\x06 \x03(\v2\x1b.docksphinx.v1.ComposeGroupR\x06groups\x129\n" +
	"\rrecent_events\x18\a \x03(\v2\x14.docksphinx.v1.EventR\frecentEvents\x12\x17\n" +
	"\aat_unix\x18\b \x01(\x03R\x06atUnix\x1a[\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.docksphinx.v1.ContainerMetricsR\x05value:\x028\x01\"~\n" +
	"\fStreamUpdate\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x17.docksphinx.v1.SnapshotH\x00R\bsnapshot\x12,\n" +
	"\x05event\x18\x02 \x01(\v2\x14.docksphinx.v1.EventH\x00R\x05eventB\t\n" +
	"\apayload\"\x14\n" +
	"\x12GetSnapshotRequest\"I\n" +
	"\rStreamRequest\x128\n" +
	"\x18include_initial_snapshot\x18\x01 \x01(\bR\x16includeInitialSnapshot2\xa5\x01\n" +
	"\x11DocksphinxService\x12I\n" +
	"\vGetSnapshot\x12!.docksphinx.v1.GetSnapshotRequest\x1a\x17.docksphinx.v1.Snapshot\x12E\n" +
	"\x06Stream\x12\x1c.docksphinx.v1.StreamRequest\x1a\x1b.docksphinx.v1.StreamUpdate0\x01B\x1eZ\x1cdocksphinx/api/docksphinx/v1b\x06proto3"

var (
	file_docksphinx_v1_docksphinx_proto_rawDescOnce sync.Once
	file_docksphinx_v1_docksphinx_proto_rawDescData []byte
)

func file_docksphinx_v1_docksphinx_proto_rawDescGZIP() []byte {
	file_docksphinx_v1_docksphinx_proto_rawDescOnce.Do(func() {
		file_docksphinx_v1_docksphinx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docksphinx_v1_docksphinx_proto_rawDesc), len(file_docksphinx_v1_docksphinx_proto_rawDesc)))
	})
	return file_docksphinx_v1_docksphinx_proto_rawDescData
}

var file_docksphinx_v1_docksphinx_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_docksphinx_v1_docksphinx_proto_goTypes = []any{
	(*ContainerInfo)(nil),      // 0: docksphinx.v1.ContainerInfo
	(*ContainerMetrics)(nil),   // 1: docksphinx.v1.ContainerMetrics
	(*ImageInfo)(nil),          // 2: docksphinx.v1.ImageInfo
	(*NetworkInfo)(nil),        // 3: docksphinx.v1.NetworkInfo
	(*VolumeInfo)(nil),         // 4: docksphinx.v1.VolumeInfo
	(*ComposeGroup)(nil),       // 5: docksphinx.v1.ComposeGroup
	(*Event)(nil),              // 6: docksphinx.v1.Event
	(*Snapshot)(nil),           // 7: docksphinx.v1.Snapshot
	(*StreamUpdate)(nil),       // 8: docksphinx.v1.StreamUpdate
	(*GetSnapshotRequest)(nil), // 9: docksphinx.v1.GetSnapshotRequest
	(*StreamRequest)(nil),      // 10: docksphinx.v1.StreamRequest
	nil,                        // 11: docksphinx.v1.Event.DataEntry
	nil,                        // 12: docksphinx.v1.Snapshot.MetricsEntry
}
var file_docksphinx_v1_docksphinx_proto_depIdxs = []int32{
	11, // 0: docksphinx.v1.Event.data:type_name -> docksphinx.v1.Event.DataEntry
	0,  // 1: docksphinx.v1.Snapshot.containers:type_name -> docksphinx.v1.ContainerInfo
	12, // 2: docksphinx.v1.Snapshot.metrics:type_name -> docksphinx.v1.Snapshot.MetricsEntry
	2,  // 3: docksphinx.v1.Snapshot.images:type_name -> docksphinx.v1.ImageInfo
	3,  // 4: docksphinx.v1.Snapshot.networks:type_name -> docksphinx.v1.NetworkInfo
	4,  // 5: docksphinx.v1.Snapshot.volumes:type_name -> docksphinx.v1.VolumeInfo
	5,  // 6: docksphinx.v1.Snapshot.groups:type_name -> docksphinx.v1.ComposeGroup
	6,  // 7: docksphinx.v1.Snapshot.recent_events:type_name -> docksphinx.v1.Event
	7,  // 8: docksphinx.v1.StreamUpdate.snapshot:type_name -> docksphinx.v1.Snapshot
	6,  // 9: docksphinx.v1.StreamUpdate.event:type_name -> docksphinx.v1.Event
	1,  // 10: docksphinx.v1.Snapshot.MetricsEntry.value:type_name -> docksphinx.v1.ContainerMetrics
	9,  // 11: docksphinx.v1.DocksphinxService.GetSnapshot:input_type -> docksphinx.v1.GetSnapshotRequest
	10, // 12: docksphinx.v1.DocksphinxService.Stream:input_type -> docksphinx.v1.StreamRequest
	7,  // 13: docksphinx.v1.DocksphinxService.GetSnapshot:output_type -> docksphinx.v1.Snapshot
	8,  // 14: docksphinx.v1.DocksphinxService.Stream:output_type -> docksphinx.v1.StreamUpdate
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_docksphinx_v1_docksphinx_proto_init() }
func file_docksphinx_v1_docksphinx_proto_init() {
	if File_docksphinx_v1_docksphinx_proto != nil {
		return
	}
	file_docksphinx_v1_docksphinx_proto_msgTypes[8].OneofWrappers = []any{
		(*StreamUpdate_Snapshot)(nil),
		(*StreamUpdate_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docksphinx_v1_docksphinx_proto_rawDesc), len(file_docksphinx_v1_docksphinx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docksphinx_v1_docksphinx_proto_goTypes,
		DependencyIndexes: file_docksphinx_v1_docksphinx_proto_depIdxs,
		MessageInfos:      file_docksphinx_v1_docksphinx_proto_msgTypes,
	}.Build()
	File_docksphinx_v1_docksphinx_proto = out.File
	file_docksphinx_v1_docksphinx_proto_goTypes = nil
	file_docksphinx_v1_docksphinx_proto_depIdxs = nil
}
